let express=require("express")
const { add, login, getuser, islogin, isadmin } = require("../controller/usercon")
const {addprod, upload, getprod, updprod, updpimg, deldct, upddct, delprod, addrv, search, buy}= require("../controller/pcon")
const {addcart, getcart, delcart, incqty, decqty} = require("../controller/cartcon")
let route=new express.Router()
route.post("/reg",add)
route.post("/login",login)
route.post("/addprod",upload.single('pimg'),islogin,isadmin,addprod)
route.get('/getprod',getprod)
route.put('/updprod',islogin,isadmin,updprod)
route.put('/updimg',upload.single('pimg'),islogin,isadmin,updpimg)
route.put("/deldct",islogin,isadmin,deldct)
route.put("/upddct",islogin,isadmin,upddct)
route.post("/addcart",islogin,addcart)
route.delete("/delprod/:_id/:pimg",islogin,isadmin,delprod)
route.get("/getcart/:uid",islogin,getcart)
route.get("/getuser/:_id",islogin,getuser)
route.put("/addrv",islogin,addrv)
route.delete("/delcart/:_id",delcart)
route.put("/incqty",islogin,incqty)
route.put("/decqty",islogin,decqty)
route.get("/srch/:txt",search)
route.get("/buy/:mail",islogin,buy)
module.exports=route